# Generated by Django 2.2.13 on 2020-06-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Years', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=100)),
                ('Office', models.CharField(max_length=40)),
                ('Description', models.TextField()),
            ],
        ),
    ]
