# Generated by Django 2.2.13 on 2020-06-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(choices=[('flaticon-ux-design', 'flaticon-ux-design'), ('flaticon-ideas', 'flaticon-ideas'), ('flaticon-flasks', 'flaticon-flasks'), ('flaticon-web-design', 'flaticon-web-design'), ('flaticon-analysis', 'flaticon-analysis'), ('flaticon-innovation', 'flaticon-innovation'), ('flaticon-idea', 'flaticon-idea')], default='flaticon-ideas', max_length=100),
        ),
    ]
