# Generated by Django 2.2.13 on 2020-06-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_skill_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(choices=[('flaticon-flasks', 'flaticon-flasks'), ('flaticon-web-design', 'flaticon-web-design'), ('flaticon-analysis', 'flaticon-analysis'), ('flaticon-ideas', 'flaticon-ideas'), ('flaticon-ux-design', 'flaticon-ux-design'), ('flaticon-idea', 'flaticon-idea'), ('flaticon-innovation', 'flaticon-innovation')], default='flaticon-ideas', max_length=100),
        ),
    ]
