# Generated by Django 2.2.13 on 2020-06-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_auto_20200621_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='Phone',
            new_name='Github',
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(choices=[('flaticon-web-design', 'flaticon-web-design'), ('flaticon-flasks', 'flaticon-flasks'), ('flaticon-idea', 'flaticon-idea'), ('flaticon-ux-design', 'flaticon-ux-design'), ('flaticon-analysis', 'flaticon-analysis'), ('flaticon-ideas', 'flaticon-ideas'), ('flaticon-innovation', 'flaticon-innovation')], default='flaticon-ideas', max_length=100),
        ),
    ]
