# Generated by Django 2.2.13 on 2020-06-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0006_auto_20200621_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='Instagram',
            field=models.CharField(default='@gresiandraputra', max_length=30),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='Twitter',
            field=models.CharField(default='@gresiandra', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(choices=[('flaticon-ideas', 'flaticon-ideas'), ('flaticon-web-design', 'flaticon-web-design'), ('flaticon-ux-design', 'flaticon-ux-design'), ('flaticon-innovation', 'flaticon-innovation'), ('flaticon-analysis', 'flaticon-analysis'), ('flaticon-idea', 'flaticon-idea'), ('flaticon-flasks', 'flaticon-flasks')], default='flaticon-ideas', max_length=100),
        ),
    ]
