# Generated by Django 2.2.13 on 2020-06-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0010_auto_20200630_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='ImageCover',
            new_name='ImageCover1',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='ImageCover2',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(choices=[('flaticon-analysis', 'flaticon-analysis'), ('flaticon-ideas', 'flaticon-ideas'), ('flaticon-innovation', 'flaticon-innovation'), ('flaticon-web-design', 'flaticon-web-design'), ('flaticon-flasks', 'flaticon-flasks'), ('flaticon-ux-design', 'flaticon-ux-design'), ('flaticon-idea', 'flaticon-idea')], default='flaticon-ideas', max_length=100),
        ),
    ]
