# Generated by Django 2.2.13 on 2020-06-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0012_auto_20200630_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='Github',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='ImageCover1',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='ImageCover2',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='Instagram',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='Twitter',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(choices=[('flaticon-web-design', 'flaticon-web-design'), ('flaticon-idea', 'flaticon-idea'), ('flaticon-ideas', 'flaticon-ideas'), ('flaticon-analysis', 'flaticon-analysis'), ('flaticon-innovation', 'flaticon-innovation'), ('flaticon-ux-design', 'flaticon-ux-design'), ('flaticon-flasks', 'flaticon-flasks')], default='flaticon-ideas', max_length=100),
        ),
    ]
