# Generated by Django 2.2.13 on 2020-06-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0013_auto_20200630_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(choices=[('flaticon-web-design', 'flaticon-web-design'), ('flaticon-idea', 'flaticon-idea'), ('flaticon-ux-design', 'flaticon-ux-design'), ('flaticon-innovation', 'flaticon-innovation'), ('flaticon-ideas', 'flaticon-ideas'), ('flaticon-analysis', 'flaticon-analysis'), ('flaticon-flasks', 'flaticon-flasks')], default='flaticon-ideas', max_length=100),
        ),
    ]
