# Generated by Django 2.2.13 on 2020-06-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0014_auto_20200630_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='ImageCover1',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='ImageCover2',
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='Github',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(choices=[('flaticon-flasks', 'flaticon-flasks'), ('flaticon-analysis', 'flaticon-analysis'), ('flaticon-ux-design', 'flaticon-ux-design'), ('flaticon-idea', 'flaticon-idea'), ('flaticon-innovation', 'flaticon-innovation'), ('flaticon-ideas', 'flaticon-ideas'), ('flaticon-web-design', 'flaticon-web-design')], default='flaticon-ideas', max_length=100),
        ),
    ]
