# Generated by Django 2.2.13 on 2020-06-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0018_auto_20200630_0851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='twitterInstagram',
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(choices=[('flaticon-flasks', 'flaticon-flasks'), ('flaticon-innovation', 'flaticon-innovation'), ('flaticon-web-design', 'flaticon-web-design'), ('flaticon-ideas', 'flaticon-ideas'), ('flaticon-analysis', 'flaticon-analysis'), ('flaticon-ux-design', 'flaticon-ux-design'), ('flaticon-idea', 'flaticon-idea')], default='flaticon-ideas', max_length=100),
        ),
    ]
