# Generated by Django 2.2.13 on 2020-07-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0019_auto_20200630_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='Title',
            new_name='Degree',
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(choices=[('flaticon-flasks', 'flaticon-flasks'), ('flaticon-ux-design', 'flaticon-ux-design'), ('flaticon-analysis', 'flaticon-analysis'), ('flaticon-web-design', 'flaticon-web-design'), ('flaticon-idea', 'flaticon-idea'), ('flaticon-innovation', 'flaticon-innovation'), ('flaticon-ideas', 'flaticon-ideas')], default='flaticon-ideas', max_length=100),
        ),
    ]
